apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# 引入需要部署的资源
- ../../base/deployment.yaml
# 部署的空间
namespace: dev
# 修改镜像
#images:
#- name: cnych/gitops-webapp
#  newTag: 3f520d48
# 修改副本数量
replicas:
- name: nginx
  count: 1
# name增加前缀
namePrefix: dev-
